// Custom Cypress commands for {{ $baseUrl }}
// Generated by SignalDeck CI — https://signaldeck.io

const selectors = require('../fixtures/selectors.json');

/**
 * Log in with the test account credentials.
 */
Cypress.Commands.add('login', (email = '{{ $testEmail }}', password = '{{ $testPassword }}') => {
  cy.session([email, password], () => {
    cy.visit('/customer/account/login');
    cy.get(selectors.auth.email_input).type(email);
    cy.get(selectors.auth.password_input).type(password);
    cy.get(selectors.auth.sign_in_button).click();
    cy.get(selectors.auth.account_link).should('exist');
  });
});

/**
 * Log out the current session.
 */
Cypress.Commands.add('logout', () => {
  cy.get(selectors.auth.logout_link).click();
});

/**
 * Add a product to the cart by visiting a given URL.
 */
Cypress.Commands.add('addProductToCart', (productUrl) => {
  cy.visit(productUrl);
  cy.get(selectors.add_to_cart.add_to_cart_button).click();
  cy.get(selectors.add_to_cart.success_message).should('be.visible');
});
