// Generated by SignalDeck CI — Account Registration Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}
//
// NOTE: Registration creates a real account. Use a unique email each run or clean up after.
// Consider using a timestamp-based email: test+${Date.now()}@example.com

const sel = require('../fixtures/selectors.json').account_registration;

describe('Account Registration', () => {
  const uniqueEmail = `test+${Date.now()}@example.com`;

  beforeEach(() => {
    cy.visit('/customer/account/create');
  });

  it('registration page loads', () => {
    cy.get(sel.register_form).should('be.visible');
  });

  it('displays all required fields', () => {
    cy.get(sel.firstname).should('be.visible');
    cy.get(sel.lastname).should('be.visible');
    cy.get(sel.email).should('be.visible');
    cy.get(sel.password).should('be.visible');
    cy.get(sel.password_confirm).should('be.visible');
  });

  it('shows a validation error for mismatched passwords', () => {
    cy.get(sel.firstname).type('Test');
    cy.get(sel.lastname).type('User');
    cy.get(sel.email).type(uniqueEmail);
    cy.get(sel.password).type('Password1!');
    cy.get(sel.password_confirm).type('WrongPassword!');
    cy.get(sel.submit_button).click();
    cy.get('body').should('contain.text', 'confirm');
  });

  it('can register a new account with valid details', () => {
    cy.get(sel.firstname).type('Test');
    cy.get(sel.lastname).type('User');
    cy.get(sel.email).type(uniqueEmail);
    cy.get(sel.password).type('Password1!');
    cy.get(sel.password_confirm).type('Password1!');
    cy.get(sel.submit_button).click();
    cy.get(sel.success_message, { timeout: 10000 }).should('be.visible');
  });
});
