// Generated by SignalDeck CI — Add to Cart Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

const sel = require('../fixtures/selectors.json');

describe('Add to Cart', () => {
  // Update this URL with a real simple product path
  const productUrl = '/simple-product.html';

  beforeEach(() => {
    cy.visit(productUrl);
  });

  it('add to cart button is visible and enabled', () => {
    cy.get(sel.add_to_cart.add_to_cart_button)
      .should('be.visible')
      .and('not.be.disabled');
  });

  it('clicking add to cart shows a success message', () => {
    cy.get(sel.add_to_cart.add_to_cart_button).click();
    cy.get(sel.add_to_cart.success_message, { timeout: 10000 }).should('be.visible');
  });

  it('cart count increments after adding a product', () => {
    cy.get(sel.homepage.cart_count).invoke('text').then((initialCount) => {
      const before = parseInt(initialCount.trim()) || 0;
      cy.get(sel.add_to_cart.add_to_cart_button).click();
      cy.get(sel.add_to_cart.success_message, { timeout: 10000 }).should('be.visible');
      cy.get(sel.homepage.cart_count, { timeout: 10000 }).invoke('text').then((afterCount) => {
        const after = parseInt(afterCount.trim()) || 0;
        expect(after).to.be.greaterThan(before);
      });
    });
  });
});
