// Generated by SignalDeck CI — Authentication Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}
//
// Ensure the test account exists: {{ $testEmail }}

const sel = require('../fixtures/selectors.json').auth;

describe('Authentication', () => {
  describe('Login', () => {
    beforeEach(() => {
      cy.visit('/customer/account/login');
    });

    it('login page loads', () => {
      cy.get(sel.login_form).should('be.visible');
    });

    it('shows an error for invalid credentials', () => {
      cy.get(sel.email_input).type('invalid@example.com');
      cy.get(sel.password_input).type('wrongpassword');
      cy.get(sel.sign_in_button).click();
      cy.get(sel.login_error, { timeout: 10000 }).should('be.visible');
    });

    it('logs in with valid credentials', () => {
      cy.get(sel.email_input).type('{{ $testEmail }}');
      cy.get(sel.password_input).type('{{ $testPassword }}');
      cy.get(sel.sign_in_button).click();
      cy.url({ timeout: 10000 }).should('not.include', 'login');
      cy.get(sel.account_link, { timeout: 10000 }).should('be.visible');
    });
  });

  describe('Logout', () => {
    beforeEach(() => {
      cy.login();
      cy.visit('/customer/account');
    });

    it('can log out', () => {
      cy.get(sel.logout_link).click();
      cy.url({ timeout: 10000 }).should('not.include', 'account');
      cy.get(sel.account_link).should('not.exist');
    });
  });
});
