// Generated by SignalDeck CI — Cart Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

const sel = require('../fixtures/selectors.json');

describe('Cart', () => {
  const productUrl = '/simple-product.html';

  beforeEach(() => {
    // Add a product then navigate to the cart
    cy.visit(productUrl);
    cy.get(sel.add_to_cart.add_to_cart_button).click();
    cy.get(sel.add_to_cart.success_message, { timeout: 10000 }).should('be.visible');
    cy.visit('/checkout/cart');
  });

  it('displays the cart with at least one item', () => {
    cy.get(sel.cart.cart_item).should('have.length.greaterThan', 0);
  });

  it('displays a cart subtotal', () => {
    cy.get(sel.cart.cart_subtotal).should('be.visible');
  });

  it('checkout button is visible', () => {
    cy.get(sel.cart.checkout_button).should('be.visible');
  });

  it('can update item quantity', () => {
    cy.get(sel.cart.qty_input).first().clear().type('2');
    cy.get(sel.cart.update_cart).first().click();
    cy.get(sel.cart.cart_subtotal, { timeout: 10000 }).should('be.visible');
  });

  it('can remove an item from the cart', () => {
    cy.get(sel.cart.cart_item).then(($items) => {
      const initialCount = $items.length;
      cy.get(sel.cart.remove_item).first().click();
      if (initialCount > 1) {
        cy.get(sel.cart.cart_item, { timeout: 10000 }).should('have.length', initialCount - 1);
      } else {
        cy.get(sel.cart.cart_container, { timeout: 10000 }).should('exist');
      }
    });
  });
});
