// Generated by SignalDeck CI — Category / PLP Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

const sel = require('../fixtures/selectors.json').category;

describe('Category / Product Listing Page', () => {
  beforeEach(() => {
    // Navigate via the first nav link — adjust if you have a specific category URL
    cy.visit('/');
    cy.get(sel.product_item).first().then(() => {
      // Already on a category or return to home
    });
  });

  it('displays a category title', () => {
    cy.visit('/');
    cy.get(sel.category_title).should('exist');
  });

  it('lists products on a category page', () => {
    cy.get(sel.product_item).should('have.length.greaterThan', 0);
  });

  it('product items have clickable links', () => {
    cy.get(sel.product_link).first().should('have.attr', 'href').and('not.be.empty');
  });

  it('sort dropdown is present', () => {
    cy.get('body').then(($body) => {
      if ($body.find(sel.sort_dropdown).length) {
        cy.get(sel.sort_dropdown).should('be.visible');
      }
    });
  });

  it('clicking a product navigates to its detail page', () => {
    cy.get(sel.product_link).first().click();
    cy.url().should('not.equal', Cypress.config('baseUrl') + '/');
  });
});
