// Generated by SignalDeck CI — Guest Checkout Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}
//
// NOTE: Guest checkout tests place real orders. Use a sandbox/staging environment.
// Update product URL and address details below before running.

const sel = require('../fixtures/selectors.json');

describe('Guest Checkout', () => {
  const productUrl = '/simple-product.html';

  const address = {
    email:     '{{ $testEmail }}',
    firstname: 'Test',
    lastname:  'Guest',
    street:    '1 Test Street',
    city:      'London',
    postcode:  'SW1A 1AA',
    phone:     '07700900000',
  };

  beforeEach(() => {
    cy.visit(productUrl);
    cy.get(sel.add_to_cart.add_to_cart_button).click();
    cy.get(sel.add_to_cart.success_message, { timeout: 10000 }).should('be.visible');
    cy.visit('/checkout');
  });

  it('checkout page loads for a guest', () => {
    cy.url().should('include', 'checkout');
  });

  it('can fill in email and shipping address', () => {
    cy.get(sel.guest_checkout.email_input, { timeout: 10000 }).type(address.email);
    cy.get(sel.guest_checkout.firstname).type(address.firstname);
    cy.get(sel.guest_checkout.lastname).type(address.lastname);
    cy.get(sel.guest_checkout.street).type(address.street);
    cy.get(sel.guest_checkout.city).type(address.city);
    cy.get(sel.guest_checkout.postcode).type(address.postcode);
    cy.get(sel.guest_checkout.phone).type(address.phone);
  });

  // Uncomment to test full order placement in a sandbox environment
  // it('can place an order as a guest', () => {
  //   // ... fill address, select shipping, select payment, submit
  //   cy.get(sel.guest_checkout.place_order_button).click();
  //   cy.get(sel.guest_checkout.success_heading, { timeout: 20000 }).should('be.visible');
  // });
});
