// Generated by SignalDeck CI — Homepage Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

const sel = require('../fixtures/selectors.json').homepage;

describe('Homepage', () => {
  beforeEach(() => {
    cy.visit('/');
  });

  it('loads successfully', () => {
    cy.url().should('include', '{{ $baseUrl }}');
    cy.title().should('not.be.empty');
  });

  it('displays the main navigation', () => {
    cy.get(sel.nav_menu).should('be.visible');
  });

  it('displays the search input', () => {
    cy.get(sel.search_input).should('be.visible');
  });

  it('displays the cart icon', () => {
    cy.get(sel.cart_icon).should('be.visible');
  });

  it('displays a hero banner or featured section', () => {
    cy.get('body').then(($body) => {
      const heroSelector = sel.hero_banner;
      if ($body.find(heroSelector).length) {
        cy.get(heroSelector).should('be.visible');
      }
    });
  });
});
