// Generated by SignalDeck CI — Product Detail Page Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

const sel = require('../fixtures/selectors.json').product;

describe('Product Detail Page (PDP)', () => {
  // Update this URL with a real product path from your store
  const productUrl = '/simple-product.html';

  beforeEach(() => {
    cy.visit(productUrl);
  });

  it('displays the product title', () => {
    cy.get(sel.product_title).should('be.visible').and('not.be.empty');
  });

  it('displays a product price', () => {
    cy.get(sel.product_price).should('be.visible');
  });

  it('displays a quantity input', () => {
    cy.get(sel.qty_input).should('be.visible');
  });

  it('quantity input defaults to 1', () => {
    cy.get(sel.qty_input).should('have.value', '1');
  });

  it('product gallery is present', () => {
    cy.get('body').then(($body) => {
      if ($body.find(sel.product_gallery).length) {
        cy.get(sel.product_gallery).should('be.visible');
      }
    });
  });

  it('page title matches the product name', () => {
    cy.get(sel.product_title).invoke('text').then((name) => {
      cy.title().should('include', name.trim());
    });
  });
});
