// Generated by SignalDeck CI — Search Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

const sel = require('../fixtures/selectors.json');

describe('Search', () => {
  // Update with a search term that returns results in your store
  const searchTerm = 'shirt';
  const noResultsTerm = 'xzqwerty12345notaproduct';

  beforeEach(() => {
    cy.visit('/');
  });

  it('search input is visible on the homepage', () => {
    cy.get(sel.homepage.search_input).should('be.visible');
  });

  it('can submit a search and see results', () => {
    cy.get(sel.homepage.search_input).type(searchTerm);
    cy.get(sel.search.search_button).click();
    cy.get(sel.search.product_item, { timeout: 10000 }).should('have.length.greaterThan', 0);
  });

  it('search results contain clickable product links', () => {
    cy.get(sel.homepage.search_input).type(searchTerm);
    cy.get(sel.search.search_button).click();
    cy.get(sel.search.product_link, { timeout: 10000 })
      .first()
      .should('have.attr', 'href')
      .and('not.be.empty');
  });

  it('clicking a search result navigates to the product', () => {
    cy.get(sel.homepage.search_input).type(searchTerm);
    cy.get(sel.search.search_button).click();
    cy.get(sel.search.product_link, { timeout: 10000 }).first().click();
    cy.get(sel.product.product_title, { timeout: 10000 }).should('be.visible');
  });

  it('shows a no-results message for an unrecognised term', () => {
    cy.get(sel.homepage.search_input).type(noResultsTerm);
    cy.get(sel.search.search_button).click();
    cy.get('body').then(($body) => {
      if ($body.find(sel.search.no_results).length) {
        cy.get(sel.search.no_results).should('be.visible');
      }
    });
  });
});
