// Generated by SignalDeck CI — Account Registration Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const sel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

test.describe('Account Registration', () => {
  const uniqueEmail = `test+${Date.now()}@example.com`;

  test.beforeEach(async ({ page }) => {
    await page.goto('/customer/account/create');
  });

  test('registration page loads', async ({ page }) => {
    await expect(page.locator(sel.register_form)).toBeVisible();
  });

  test('displays all required fields', async ({ page }) => {
    await expect(page.locator(sel.firstname)).toBeVisible();
    await expect(page.locator(sel.lastname)).toBeVisible();
    await expect(page.locator(sel.email)).toBeVisible();
    await expect(page.locator(sel.password)).toBeVisible();
    await expect(page.locator(sel.password_confirm)).toBeVisible();
  });

  test('shows an error for mismatched passwords', async ({ page }) => {
    await page.locator(sel.firstname).fill('Test');
    await page.locator(sel.lastname).fill('User');
    await page.locator(sel.email).fill(uniqueEmail);
    await page.locator(sel.password).fill('Password1!');
    await page.locator(sel.password_confirm).fill('WrongPassword!');
    await page.locator(sel.submit_button).click();
    await expect(page.locator('body')).toContainText('confirm');
  });

  test('can register a new account', async ({ page }) => {
    await page.locator(sel.firstname).fill('Test');
    await page.locator(sel.lastname).fill('User');
    await page.locator(sel.email).fill(uniqueEmail);
    await page.locator(sel.password).fill('Password1!');
    await page.locator(sel.password_confirm).fill('Password1!');
    await page.locator(sel.submit_button).click();
    await expect(page.locator(sel.success_message)).toBeVisible({ timeout: 10000 });
  });
});
