// Generated by SignalDeck CI — Authentication Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}
//
// Ensure the test account exists: {{ $testEmail }}

import { test, expect } from '@playwright/test';

const sel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

test.describe('Login', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/customer/account/login');
  });

  test('login page loads', async ({ page }) => {
    await expect(page.locator(sel.login_form)).toBeVisible();
  });

  test('shows an error for invalid credentials', async ({ page }) => {
    await page.locator(sel.email_input).fill('invalid@example.com');
    await page.locator(sel.password_input).fill('wrongpassword');
    await page.locator(sel.sign_in_button).click();
    await expect(page.locator(sel.login_error)).toBeVisible({ timeout: 10000 });
  });

  test('logs in with valid credentials', async ({ page }) => {
    await page.locator(sel.email_input).fill('{{ $testEmail }}');
    await page.locator(sel.password_input).fill('{{ $testPassword }}');
    await page.locator(sel.sign_in_button).click();
    await expect(page).not.toHaveURL(/login/, { timeout: 10000 });
    await expect(page.locator(sel.account_link)).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Logout', () => {
  test.beforeEach(async ({ page }) => {
    // Log in programmatically
    await page.goto('/customer/account/login');
    await page.locator(sel.email_input).fill('{{ $testEmail }}');
    await page.locator(sel.password_input).fill('{{ $testPassword }}');
    await page.locator(sel.sign_in_button).click();
    await expect(page).not.toHaveURL(/login/, { timeout: 10000 });
    await page.goto('/customer/account');
  });

  test('can log out', async ({ page }) => {
    await page.locator(sel.logout_link).click();
    await expect(page).not.toHaveURL(/account/, { timeout: 10000 });
  });
});
