// Generated by SignalDeck CI — Category / PLP Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const sel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

test.describe('Category / Product Listing Page', () => {
  test('lists products on a category page', async ({ page }) => {
    await page.goto('/');
    const products = page.locator(sel.product_item);
    await expect(products.first()).toBeVisible({ timeout: 10000 });
    expect(await products.count()).toBeGreaterThan(0);
  });

  test('product items have clickable links', async ({ page }) => {
    await page.goto('/');
    const link = page.locator(sel.product_link).first();
    const href = await link.getAttribute('href');
    expect(href).toBeTruthy();
  });

  test('sort dropdown is present when available', async ({ page }) => {
    await page.goto('/');
    const sort = page.locator(sel.sort_dropdown);
    if (await sort.count() > 0) {
      await expect(sort.first()).toBeVisible();
    }
  });

  test('clicking a product navigates to its detail page', async ({ page }) => {
    await page.goto('/');
    const initialUrl = page.url();
    await page.locator(sel.product_link).first().click();
    await expect(page).not.toHaveURL(initialUrl);
  });
});
