// Generated by SignalDeck CI — Homepage Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const sel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

test.describe('Homepage', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('loads successfully', async ({ page }) => {
    await expect(page).toHaveURL(/{{ preg_quote(parse_url($baseUrl, PHP_URL_HOST), '/') }}/);
    await expect(page).toHaveTitle(/.+/);
  });

  test('displays the main navigation', async ({ page }) => {
    await expect(page.locator(sel.nav_menu)).toBeVisible();
  });

  test('displays the search input', async ({ page }) => {
    await expect(page.locator(sel.search_input)).toBeVisible();
  });

  test('displays the cart icon', async ({ page }) => {
    await expect(page.locator(sel.cart_icon)).toBeVisible();
  });

  test('displays a hero banner or featured section', async ({ page }) => {
    const hero = page.locator(sel.hero_banner);
    if (await hero.count() > 0) {
      await expect(hero.first()).toBeVisible();
    }
  });
});
