// Generated by SignalDeck CI — Product Detail Page Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const sel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

// Update this URL with a real product path from your store
const productUrl = '/simple-product.html';

test.describe('Product Detail Page (PDP)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(productUrl);
  });

  test('displays the product title', async ({ page }) => {
    await expect(page.locator(sel.product_title)).toBeVisible();
    await expect(page.locator(sel.product_title)).not.toHaveText('');
  });

  test('displays a product price', async ({ page }) => {
    await expect(page.locator(sel.product_price)).toBeVisible();
  });

  test('quantity input defaults to 1', async ({ page }) => {
    await expect(page.locator(sel.qty_input)).toHaveValue('1');
  });

  test('product gallery is present when available', async ({ page }) => {
    const gallery = page.locator(sel.product_gallery);
    if (await gallery.count() > 0) {
      await expect(gallery.first()).toBeVisible();
    }
  });

  test('page title includes the product name', async ({ page }) => {
    const productName = await page.locator(sel.product_title).textContent();
    await expect(page).toHaveTitle(new RegExp(productName!.trim().substring(0, 20)));
  });
});
